- name: Install MySQL
  user: azureuser
  hosts: mysqlserver
  become: True
  become_user: root
  vars:
    MySQL_root_pass: ReplaceWithYourPassword
  tasks:
    - name: test installation
      apt:   package={{   item   }}   state=present   force=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"
      with_items:
        - mysql-server
        - mysql-client

